### PR TITLE
evergreen for 2019

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/add-in-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/elizs-evergreen/docs/add-ins/add-in-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201809241832428011-379%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xEqNpHmT9ObTvDtW6U4aFlccNSjR9dkaD8oaIAbW6zM%3D&st=2018-09-24T18%3A28%3A44Z&se=2018-10-25T18%3A33%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@ElizabethSamuel-MSFT  just curious why you're adding me as reviewer on PRs like this?  Is this something that you're not comfortable reviewing?

**Comment by ElizabethSamuel-MSFT** [comment]
@kbrandl No, nothing like that. But we hadn't discussed any PR procedures in this repo so I sent out just in case.

**Comment by kbrandl** [comment]
@ElizabethSamuel-MSFT Ok, cool...thanks for being proactive about this! Perhaps we can chat next week when you're back in the office re PR procedures for this particular repo.  Thanks!

**Pull request merged**
