### PR TITLE
Update signed card section with sample links

### PR DESCRIPTION
**Pull request by tony-zhu**

### CODE REVIEW

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[5c85e88](https://github.com/tony-zhu/outlook-dev-docs/pull/468/commits/5c85e885ff1b01cc695382ef965e647ef0c933b3)_: 

:clock10: **Preparing**: average preparing time is _41 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[5c85e88](https://github.com/tony-zhu/outlook-dev-docs/pull/468/commits/5c85e885ff1b01cc695382ef965e647ef0c933b3)_: 

:clock10: **Incremental building**: average incremental building time is _18 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[5c85e88](https://github.com/tony-zhu/outlook-dev-docs/pull/468/commits/5c85e885ff1b01cc695382ef965e647ef0c933b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/actionable-messages/security-requirements.md](https://github.com/tony-zhu/outlook-dev-docs/blob/patch-6/docs/actionable-messages/security-requirements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201812202342224622-468%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CY9KjNWjph1H2TDmXHCjIBjJKSXnVCwu5WBWq4HK8AQ%3D&st=2018-12-20T23%3A38%3A23Z&se=2019-01-20T23%3A43%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@jasonjoh FYI - since this PR updates an Actionable Messages article, I've assigned you as reviewer. Thanks!

**Pull request merged**
