### PR TITLE
[Admin] (CATS) Fix issues from August 2019 report.

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[d55699d](https://github.com/OfficeDev/outlook-dev-docs/commits/d55699d1d22c92e22e15493f5714867432056c3b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-fix-CATS-issues-201908/docs/actionable-messages/index.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C7%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201908071854294741-666%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=470tie1QvWZUCCTxdPpiLySO0TeD177Nidvp3bVsYGY%3D&st=2019-08-07T18%3A50%3A25Z&se=2019-09-07T18%3A55%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@kbrandl Hi, LMK when this is merged and I'll publish. Or, feel free to go ahead and merge to live. FYI, I haven't published this repo yet this week, and thought I'd wait until you completed this merge. Either way works, Thanks

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT Actually, I did publish this repo this morning.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Okay, GTK! We still need to republish to incorporate Kim's CATS fixes that are waiting to be merged to master. Thanks, lindalu

**Pull request merged**
