### PR TITLE
AMP for Email Docs

### PR DESCRIPTION
**Pull request by LezaMax**
Publishing AMP for Email docs for the preview

### CODE REVIEW

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[6d0c5e1](https://github.com/OfficeDev/outlook-dev-docs/commits/6d0c5e13ee3e3992e0c3fbd653e7b41ed75dd1e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/amphtml/authentication.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/authentication.md) | :white_check_mark:Succeeded | |
[docs/amphtml/best-practices.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/best-practices.md) | :white_check_mark:Succeeded | |
[docs/amphtml/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/get-started.md) | :white_check_mark:Succeeded | |
[docs/amphtml/images/dynamic-settings.png](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/images/dynamic-settings.png) | :white_check_mark:Succeeded | |
[docs/amphtml/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/index.md) | :white_check_mark:Succeeded | |
[docs/amphtml/register-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/register-outlook.md) | :white_check_mark:Succeeded | |
[docs/amphtml/security-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/security-requirements.md) | :white_check_mark:Succeeded | |
[docs/amphtml/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/toc.yml) | :white_check_mark:Succeeded | |
[docs/amphtml/version-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/version-support.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C4%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201909041633248155-690%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iikExibyI6xBSXAlUhm1KX2J4ubvzIbFwiMQXASHIJ4%3D&st=2019-09-04T16%3A29%3A29Z&se=2019-10-05T16%3A34%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LezaMax** [comment]
Publishing AMP for Email docs for the preview

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[6d0c5e1](https://github.com/OfficeDev/outlook-dev-docs/commits/6d0c5e13ee3e3992e0c3fbd653e7b41ed75dd1e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/amphtml/authentication.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/authentication.md) | :white_check_mark:Succeeded | |
[docs/amphtml/best-practices.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/best-practices.md) | :white_check_mark:Succeeded | |
[docs/amphtml/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/get-started.md) | :white_check_mark:Succeeded | |
[docs/amphtml/images/dynamic-settings.png](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/images/dynamic-settings.png) | :white_check_mark:Succeeded | |
[docs/amphtml/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/index.md) | :white_check_mark:Succeeded | |
[docs/amphtml/register-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/register-outlook.md) | :white_check_mark:Succeeded | |
[docs/amphtml/security-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/security-requirements.md) | :white_check_mark:Succeeded | |
[docs/amphtml/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/toc.yml) | :white_check_mark:Succeeded | |
[docs/amphtml/version-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/version-support.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C4%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201909041634056843-690%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6TXfPON4BfXEzaeWuco4rGpR9MvoftNodLg5mrdzuR8%3D&st=2019-09-04T16%3A30%3A37Z&se=2019-10-05T16%3A35%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasonjoh** [comment]
Docs Build status updates of commit _[44efed8](https://github.com/OfficeDev/outlook-dev-docs/commits/44efed8043cbeb2465e26a5e709f6bb83d8993cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/amphtml/authentication.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/authentication.md) | :white_check_mark:Succeeded | |
[docs/amphtml/best-practices.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/best-practices.md) | :white_check_mark:Succeeded | |
[docs/amphtml/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/get-started.md) | :white_check_mark:Succeeded | |
[docs/amphtml/images/dynamic-settings.png](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/images/dynamic-settings.png) | :white_check_mark:Succeeded | |
[docs/amphtml/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/index.md) | :white_check_mark:Succeeded | |
[docs/amphtml/register-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/register-outlook.md) | :white_check_mark:Succeeded | |
[docs/amphtml/security-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/security-requirements.md) | :white_check_mark:Succeeded | |
[docs/amphtml/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/toc.yml) | :white_check_mark:Succeeded | |
[docs/amphtml/version-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/amphtml/version-support.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/outlook-dev-docs/blob/amphtml/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C4%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201909041710230168-690%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2YhT6SlZviBpF%2BJtDAgiNpVbmYmvRM0VtDbUBbYXOXc%3D&st=2019-09-04T17%3A06%3A27Z&se=2019-10-05T17%3A11%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
