### PR TITLE
Add Visual Studio guidance to quickstart

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/quick-start.md](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C20%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201712200326392589-137%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=i8V30ceQVkcfX%2FEtwrb15vT%2F4fQ7bIFNnOYiTWvyQk0%3D&st=2017-12-20T03%3A22%3A21Z&se=2018-01-20T03%3A27%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@jasonjoh -- please test/verify the Visual Studio guidance in this article before merging this PR (by attempting to use the instructions to create/test the add-in). I had some trouble getting my VS project to run, but believe it's due to a configuration issue on my part, not due to an issue with the instructions -- but I'd suggest that you confirm.

Also -- note that I made a change to the "Any editor" section of the article re guidance about the Certificate that Yo Office generates. FYI, Yo Office was updated (on 12/18) so that it now generates a valid certificate...you still need to go through the process of trusting the cert, but once you do that, the add-in will run via HTTPS. If you have other articles which provide guidance about using Yo Office, I'd suggest you update these articles in a similar fashion.

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/quick-start.md](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C2%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201801021833166977-137%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XnOWXVyELIH%2F1vXqP3ZGRvF%2FgbWFfe9ozoaWhOrlpEc%3D&st=2018-01-02T18%3A28%3A59Z&se=2018-02-02T18%3A33%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasonjoh** [comment]
By default the VS project opens OWA when you run it. Do we want to tell people how to change that to the Outlook desktop client?

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/images/quick-start-button-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-button-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/images/quick-start-task-pane-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-task-pane-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/quick-start.md](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201801082011110684-137%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2mrw2PnkIf%2FbgytnxAxR5juLEnXu8LJe7Dk72%2BEKBQI%3D&st=2018-01-08T20%3A06%3A53Z&se=2018-02-08T20%3A11%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/images/quick-start-button-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-button-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/images/quick-start-task-pane-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-task-pane-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/quick-start.md](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201801082015094096-137%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YIpK1OPBcR9nfmKamVJzzZkKQm9vDRgR3hN2Grhx%2BE4%3D&st=2018-01-08T20%3A11%3A11Z&se=2018-02-08T20%3A16%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/images/quick-start-button-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-button-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/images/quick-start-task-pane-owa.png](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/images/quick-start-task-pane-owa.png) | :white_check_mark:Succeeded | |
[docs/add-ins/quick-start.md](https://github.com/kbrandl/outlook-dev-docs/blob/kb-quickstart-vs-guidance/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201801082019314663-137%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YRfFD86L2eR6WZ4Ld8HHJuJs58XzAyDkpYY8n2BMp%2Bk%3D&st=2018-01-08T20%3A15%3A31Z&se=2018-02-08T20%3A20%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@jasonjoh -- I've updated the Visual Studio guidance within the quickstart to reference "Outlook on the web".  This PR should be ready to merge now; please let me know if you have any additional feedback / change requests. Thanks!

**Pull request merged**
