### PR TITLE
[Add-ins] No pinnable task panes in appointments

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**
[Internal item](https://office.visualstudio.com/OC/_workitems/edit/3013940)

### CODE REVIEW

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[b8654a9](https://github.com/OfficeDev/outlook-dev-docs/pull/521/commits/b8654a94c62540f980165911332a81b7895ddbbd)_: 

:clock10: **Preparing**: average preparing time is _41 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[b8654a9](https://github.com/OfficeDev/outlook-dev-docs/pull/521/commits/b8654a94c62540f980165911332a81b7895ddbbd)_: 

:clock10: **Incremental building**: average incremental building time is _18 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[b8654a9](https://github.com/OfficeDev/outlook-dev-docs/pull/521/commits/b8654a94c62540f980165911332a81b7895ddbbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/add-ins/pinnable-taskpane.md](https://github.com/OfficeDev/outlook-dev-docs/blob/elizs-update-pinnable/docs/add-ins/pinnable-taskpane.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C8%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201902081655163597-521%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e%2Fr8a5PZ0TpBn5NYNB1VPvL%2BetnuvYOXwJe0lg3n6qY%3D&st=2019-02-08T16%3A51%3A22Z&se=2019-03-11T16%3A56%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ElizabethSamuel-MSFT** [comment]
Outlook dev approved change.

**Pull request merged**
