### PR TITLE
Update OnAuthorizationCodeReceived() method

### PR DESCRIPTION
**Pull request by SiavasFiroozbakht**
Update OnAuthorizationCodeReceived() method to reflect the changes in Microsoft.Identity.Client.
Specifically, the constructor of the ConfidentialClientApplication class, the reversal of arguments for AcquireTokenByAuthorizationCodeAsync method, and the change of Token to AccessToken in AuthenticationResult class have been considered.

### CODE REVIEW

**Comment by jasonjoh** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/rest/dotnet-tutorial.md](https://github.com/SiavasFiroozbakht/outlook-dev-docs/blob/patch-1/docs/rest/dotnet-tutorial.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C30%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201705301948315014-50%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jasonjoh** [comment]
Thanks for this @SiavasFiroozbakht! Could I get you to resubmit this to the master branch instead of live? I can't merge pull requests directly into the live branch. Sorry for the confusion!

**Comment by SiavasFiroozbakht** [comment]
This is completely fine, @jasonjoh. I have changed it to `master`.
My pleasure to contribute to the documentation.

**Comment by jasonjoh** [comment]
Thank you! I'm updating the dotnet-tutorial to the latest MSAL now to sanity check and see if any other changes are needed.

**Comment by jasonjoh** [comment]
Ah yes, they totally reworked how you work with the token cache too, so this will need other changes as well.

**Comment by jasonjoh** [comment]
Made additional changes to tutorial: https://github.com/OfficeDev/outlook-dev-docs/pull/51

**Comment by SiavasFiroozbakht** [comment]
Thank you for taking time to revise this, @jasonjoh.
The documentation is very valuable for me and other developers to use the promising Microsoft Graph API.

**Pull request merged**
