### PR TITLE
[Add-ins] (admin) Update docs metadata.

### PR DESCRIPTION
**Pull request by kbrandl**
This PR does the following:
- updates docfx.json to specify **author**, **ms.author**, and **ms.technology** metadata attribute values for all .md files in the **add-ins** folder
- removes those individual metadata attributes from all individual files in the **add-ins** folder
- removes **legacy-addins.md** (empty/obsolete file) and adds redirect for it

### CODE REVIEW

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[e0db732](https://github.com/OfficeDev/outlook-dev-docs/pull/515/commits/e0db732b24acc9ce3060536bb9aedb2080b3cfb6)_: 

:clock10: **Preparing**: average preparing time is _41 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[e0db732](https://github.com/OfficeDev/outlook-dev-docs/pull/515/commits/e0db732b24acc9ce3060536bb9aedb2080b3cfb6)_: 

:clock10: **Incremental building**: average incremental building time is _18 sec(s)_

**Comment by jasonjoh** [comment]
OPS Build status updates of commit _[e0db732](https://github.com/OfficeDev/outlook-dev-docs/pull/515/commits/e0db732b24acc9ce3060536bb9aedb2080b3cfb6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[docs/add-ins/activation-rules.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/activation-rules.md) | :white_check_mark:Succeeded | |
[docs/add-ins/add-and-remove-attachments-to-an-item-in-a-compose-form.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/add-and-remove-attachments-to-an-item-in-a-compose-form.md) | :white_check_mark:Succeeded | |
[docs/add-ins/add-in-commands-for-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/add-in-commands-for-outlook.md) | :white_check_mark:Succeeded | |
[docs/add-ins/add-in-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/add-in-requirements.md) | :white_check_mark:Succeeded | |
[docs/add-ins/add-mobile-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/add-mobile-support.md) | :white_check_mark:Succeeded | |
[docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/addin-tutorial.md) | :white_check_mark:Succeeded | |
[docs/add-ins/apis.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/apis.md) | :white_check_mark:Succeeded | |
[docs/add-ins/authenticate-a-user-with-an-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/authenticate-a-user-with-an-identity-token.md) | :white_check_mark:Succeeded | |
[docs/add-ins/authenticate-a-user-with-an-sso-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/authenticate-a-user-with-an-sso-token.md) | :white_check_mark:Succeeded | |
[docs/add-ins/authentication.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/authentication.md) | :white_check_mark:Succeeded | |
[docs/add-ins/compare-outlook-add-in-support-in-outlook-for-mac.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/compare-outlook-add-in-support-in-outlook-for-mac.md) | :white_check_mark:Succeeded | |
[docs/add-ins/compose-scenario.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/compose-scenario.md) | :white_check_mark:Succeeded | |
[docs/add-ins/contextual-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/contextual-outlook-add-ins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/extension-module-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/extension-module-outlook-add-ins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/extract-entity-strings-from-an-item.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/extract-entity-strings-from-an-item.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-and-set-item-data-in-a-compose-form.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-and-set-item-data-in-a-compose-form.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-and-set-recurrence.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-and-set-recurrence.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-attachments-of-an-outlook-item.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-attachments-of-an-outlook-item.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-or-set-the-location-of-an-appointment.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-or-set-the-location-of-an-appointment.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-or-set-the-subject.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-or-set-the-subject.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-or-set-the-time-of-an-appointment.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-or-set-the-time-of-an-appointment.md) | :white_check_mark:Succeeded | |
[docs/add-ins/get-set-or-add-recipients.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/get-set-or-add-recipients.md) | :white_check_mark:Succeeded | |
[docs/add-ins/implement-sso-in-outlook-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/implement-sso-in-outlook-add-in.md) | :white_check_mark:Succeeded | |
[docs/add-ins/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/index.md) | :white_check_mark:Succeeded | |
[docs/add-ins/insert-data-in-the-body.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/insert-data-in-the-body.md) | :white_check_mark:Succeeded | |
[docs/add-ins/inside-the-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/inside-the-identity-token.md) | :white_check_mark:Succeeded | |
[docs/add-ins/item-data.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/item-data.md) | :white_check_mark:Succeeded | |
[docs/add-ins/legacy-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/legacy-addins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/limits-for-activation-and-javascript-api-for-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/limits-for-activation-and-javascript-api-for-outlook-add-ins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/manifests.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/manifests.md) | :white_check_mark:Succeeded | |
[docs/add-ins/match-strings-in-an-item-as-well-known-entities.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/match-strings-in-an-item-as-well-known-entities.md) | :white_check_mark:Succeeded | |
[docs/add-ins/metadata-for-an-outlook-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/metadata-for-an-outlook-add-in.md) | :white_check_mark:Succeeded | |
[docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/outlook-addin-design.md) | :white_check_mark:Succeeded | |
[docs/add-ins/outlook-mobile-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/outlook-mobile-addins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/outlook-on-send-addins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/pinnable-taskpane.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/pinnable-taskpane.md) | :white_check_mark:Succeeded | |
[docs/add-ins/privacy-and-security.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/privacy-and-security.md) | :white_check_mark:Succeeded | |
[docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/quick-start.md) | :white_check_mark:Succeeded | |
[docs/add-ins/read-scenario.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/read-scenario.md) | :white_check_mark:Succeeded | |
[docs/add-ins/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/sideload-outlook-add-ins-for-testing.md) | :white_check_mark:Succeeded | |
[docs/add-ins/testing-and-tips.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/testing-and-tips.md) | :white_check_mark:Succeeded | |
[docs/add-ins/tips-for-handling-date-values-in-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/tips-for-handling-date-values-in-outlook-add-ins.md) | :white_check_mark:Succeeded | |
[docs/add-ins/troubleshoot-outlook-add-in-activation.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/troubleshoot-outlook-add-in-activation.md) | :white_check_mark:Succeeded | |
[docs/add-ins/understanding-outlook-add-in-permissions.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/understanding-outlook-add-in-permissions.md) | :white_check_mark:Succeeded | |
[docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md) | :white_check_mark:Succeeded | |
[docs/add-ins/use-rest-api.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/use-rest-api.md) | :white_check_mark:Succeeded | |
[docs/add-ins/validate-an-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/validate-an-identity-token.md) | :white_check_mark:Succeeded | |
[docs/add-ins/web-services.md](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/add-ins/web-services.md) | :white_check_mark:Succeeded | |
[docs/docfx.json](https://github.com/OfficeDev/outlook-dev-docs/blob/kb-update-add-ins-metadata/docs/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C5%5Cf49385f6-041e-c905-242e-e0025c631156%5CPullRequest%5C201902052046236210-515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5E559XWrqmKwyZjOEY7yT5pALKsaBbhIcdaSvOksvCg%3D&st=2019-02-05T20%3A42%3A28Z&se=2019-03-08T20%3A47%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@jasonjoh at long last, here's the PR to update metadata values for the Add-ins docs in **OfficeDev/outlook-dev-docs**. Can you please review? Please note the following:
- Metadata values for **ms.technology**, **ms.author**, and **author** are being specified at the folder level (i.e., for all .md files in the **add-ins** folder) in docfx.json.
- It's by design that we're using the user/account **o365devx** for the **ms.author** and **author** metadata attributes. 
- The APEX team has recently whitelisted the metadata values **ms.prod = outlook** and **ms.technology = add-ins** -- so this PR updates **ms.technology** value accordingly (**ms.prod = outlook** is already being set at the global level for this doc set, so no changes were necessary to set this metadata value).

Thanks in advance for your review!

**Pull request merged**
